# Generated by Django 4.2.2 on 2023-07-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0002_alter_organisationslotbookingmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisationslotbookingmodel',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
