# Generated by Django 4.2.2 on 2023-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0003_alter_ordermodel_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='booking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
