# Generated by Django 4.2.2 on 2023-06-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailOtpVerifyModel',
            new_name='OtpVerifyModel',
        ),
    ]
