# Generated by Django 4.2.2 on 2023-06-27 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationCategoryDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationCategoryModel_category', to='organisation.categorymodel')),
                ('description', models.ManyToManyField(blank=True, related_name='OrganisationCategoryModel_description', to='organisation.organisationcategorydescriptionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationMediaGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.URLField(blank=True, max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True)),
                ('profile', models.URLField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('org_type', models.CharField(blank=True, choices=[('DIAGNOSIS', 'DIAGNOSIS'), ('HOSPITAL', 'HOSPITAL'), ('OTHER', 'OTHER')], max_length=100, null=True)),
                ('x_coordinate', models.CharField(blank=True, max_length=100, null=True)),
                ('y_coordinate', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationModel_address', to='address.addressmodel')),
                ('media', models.ManyToManyField(blank=True, related_name='OrganisationModel_media', to='organisation.organisationmediagallerymodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationDoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationDoctorModel_category', to='organisation.organisationcategorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationDoctorModel_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organisationcategorymodel',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationCategoryModel_icon', to='organisation.organisationmediagallerymodel'),
        ),
        migrations.AddField(
            model_name='organisationcategorymodel',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='OrganisationCategoryModel_media', to='organisation.organisationmediagallerymodel'),
        ),
        migrations.AddField(
            model_name='organisationcategorymodel',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationCategoryModel_organisation', to='organisation.organisationmodel'),
        ),
    ]
