# Generated by Django 4.2.2 on 2023-06-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationdoctormodel',
            name='is_fasting',
            field=models.BooleanField(default=False),
        ),
    ]
