# Generated by Django 4.2.2 on 2023-06-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_organisationdoctormodel_is_fasting'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmodel',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationModel_icon', to='organisation.organisationmediagallerymodel'),
        ),
    ]
