# Generated by Django 4.2.2 on 2023-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_organisationdoctormodel_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdoctormodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
