# Generated by Django 4.2.2 on 2023-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_alter_organisationdoctormodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdoctormodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='organisationdoctormodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
