version: "3.8"
services:
  STPL_app_database:
    image: postgres
    restart: always

    environment:
      - POSTGRES_DB = STPL_app
      - POSTGRES_USER = STPL_app
      - POSTGRES_PASSWORD = STPL_app@123
    ports:
      - 9070:5432