# Generated by Django 4.2.2 on 2023-06-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revieworganisationdoctormodel',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='ReviewOrganisationDoctorModel_reviews', to='reviews.reviewmodel'),
        ),
        migrations.AlterField(
            model_name='revieworganisationmodel',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='ReviewOrganisationModel_reviews', to='reviews.reviewmodel'),
        ),
    ]
