# Generated by Django 4.2.3 on 2023-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_alter_organisationdoctormodel_price_and_more'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='organisation',
            field=models.ManyToManyField(blank=True, related_name='UserProfileModel_organisation', to='organisation.organisationmodel'),
        ),
    ]
